name: insul_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  http: ^1.1.2
  flutter_svg: ^2.0.9
  flutter_blue_plus: ^1.32.7
  percent_indicator: ^4.0.1
  liquid_progress_indicator: ^0.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^26.1.41+1
  align_positioned: ^4.0.1
  flutter_switch: ^0.3.2
  flutter_datetime_picker: ^1.5.1
  fl_chart: ^0.68.0
  font_awesome_flutter: ^10.7.0
  top_modal_sheet: ^2.1.0
  shared_preferences: ^2.2.3
  translator: ^1.0.0
  provider: ^6.1.2
  tuple: ^2.0.2
  table_calendar: ^3.0.9
  linear_progress_bar: ^1.1.1
  accordion: ^2.6.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  get: ^4.6.6
  dio: ^5.5.0+1
  multiselect: ^0.0.7
  getwidget: ^4.0.0
  simple_ripple_animation: ^0.0.9
  animated_icon: ^0.0.9
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  calendar_date_picker2: ^1.1.7
  pinput: ^5.0.0
  smart_auth: ^2.0.0
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Video/Adobe XD 2024-07-22 10-53-54.mp4
    
  fonts:
    - family: Suissnord
      fonts:
        # - asset: assets/fonts/SF-Pro.ttf
        - asset: assets/fonts/Suissnord.otf
        # - asset: assets/fonts/SF-Pro-Text-Light.otf
        # - asset: assets/fonts/SF-Pro-Text-Bold.otf
        # - asset: assets/fonts/SF-Pro-Text-Semibold.otf
    - family: SfLight
      fonts:
        - asset: assets/fonts/SfLight.otf
          